# Generated by Django 3.0.5 on 2020-06-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='winequaity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixedacidity', models.FloatField(max_length=10)),
                ('volatileacidity', models.FloatField(max_length=10)),
                ('citricacid', models.FloatField(max_length=10)),
                ('residualsugar', models.FloatField(max_length=10)),
                ('chlorides', models.FloatField(max_length=10)),
                ('freesulfurdioxide', models.FloatField(max_length=10)),
                ('totalsulfurdioxide', models.FloatField(max_length=10)),
                ('density', models.FloatField(max_length=10)),
                ('pH', models.FloatField(max_length=10)),
                ('sulphates', models.FloatField(max_length=10)),
                ('alcohol', models.FloatField(max_length=10)),
            ],
        ),
    ]
